auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_chunk_age: 1h

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
  filesystem:
    directory: /loki/chunks

limits_config:
  retention_period: ${LOKI_RETENTION_PERIOD:-168h}  # Настраивается через .env
  allow_structured_metadata: false
  max_streams_per_user: 10000
  max_line_size: 256000

table_manager:
  retention_deletes_enabled: true
  retention_period: ${LOKI_RETENTION_PERIOD:-168h}

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

common:
  path_prefix: /tmp/loki
