services:
  # Nginx Reverse Proxy with HTTPS
  nginx:
    image: nginx:alpine
    container_name: guide-nginx
    ports:
      - "80:80"
      - "443:443"
      - "8443:443"  # Дополнительный порт для обхода внешнего nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - api-gateway
    networks:
      - guide-network
    labels:
      logging: "enabled"
      logging.service: "nginx"
      monitoring: "enabled"
      monitoring.port: "80"
    restart: always

  # PostgreSQL with pg_jieba extension
  postgres:
    image: geronimodid/guide-for-china-mobile-postgres:latest
    container_name: guide-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    # Порт закрыт для безопасности. Для администрирования раскомментируйте:
    # ports:
    #   - "5433:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - guide-network
    labels:
      logging: "enabled"
      logging.service: "postgres"
    restart: always

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: guide-redis
    # Порт закрыт для безопасности. Для администрирования раскомментируйте:
    # ports:
    #   - "6380:6379"
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - guide-network
    command: redis-server --appendonly yes
    labels:
      logging: "enabled"
      logging.service: "redis"
    restart: always

  # MinIO for file storage
  minio:
    image: minio/minio:latest
    container_name: guide-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      # Открываем прямой доступ к MinIO для мобильного приложения
      - "9000:9000"
    expose:
      - "9001"
    volumes:
      - minio_data:/data
    networks:
      - guide-network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      logging: "enabled"
      logging.service: "minio"
    restart: always

  # User Service
  user-service:
    image: geronimodid/guide-for-china-mobile-user:latest
    container_name: guide-user-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
      PORT: 4002
      NODE_ENV: production
      CORS_ORIGIN: ${CORS_ORIGIN}
      DICTIONARY_SERVICE_HOST: dictionary-service
      DICTIONARY_SERVICE_PORT: 4001
      REDIS_HOST: redis
      REDIS_PORT: 6379
    expose:
      - "4002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - guide-network
    labels:
      logging: "enabled"
      logging.service: "user-service"
      monitoring: "enabled"
      monitoring.port: "4002"
      monitoring.path: "/metrics"
    restart: always

  # Dictionary Service
  dictionary-service:
    image: geronimodid/guide-for-china-mobile-dictionary:latest
    container_name: guide-dictionary-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 4001
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
    expose:
      - "4001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - guide-network
    labels:
      logging: "enabled"
      logging.service: "dictionary-service"
      monitoring: "enabled"
      monitoring.port: "4001"
      monitoring.path: "/metrics"
    restart: always

  # TTS Service
  tts-service:
    image: geronimodid/guide-for-china-mobile-tts:latest
    container_name: guide-tts-service
    environment:
      PORT: 4003
      NODE_ENV: production
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: tts-audio
      MINIO_PUBLIC_URL: ${MINIO_PUBLIC_URL}
    expose:
      - "4003"
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - guide-network
    labels:
      logging: "enabled"
      logging.service: "tts-service"
      monitoring: "enabled"
      monitoring.port: "4003"
      monitoring.path: "/metrics"
    restart: always

  # API Gateway
  api-gateway:
    image: geronimodid/guide-for-china-mobile-api-gateway:latest
    container_name: guide-api-gateway
    environment:
      PORT: 4000
      NODE_ENV: production
      CORS_ORIGIN: ${CORS_ORIGIN}
      USER_SERVICE_URL: http://user-service:4002/graphql
      DICTIONARY_SERVICE_URL: http://dictionary-service:4001/
      TTS_SERVICE_URL: http://tts-service:4003
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    expose:
      - "4000"
    depends_on:
      redis:
        condition: service_healthy
      user-service:
        condition: service_started
      dictionary-service:
        condition: service_started
      tts-service:
        condition: service_started
    networks:
      - guide-network
    labels:
      logging: "enabled"
      logging.service: "api-gateway"
      monitoring: "enabled"
      monitoring.port: "4000"
      monitoring.path: "/metrics"
    restart: always

  # Monitoring Services
  promtail:
    image: grafana/promtail:latest
    container_name: guide-promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/logs-and-metric/config/promtail/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    privileged: true
    environment:
      - LOGGING_ENVIRONMENT=prod
    networks:
      - guide-network
    deploy:
      resources:
        limits:
          memory: 512m
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: guide-loki
    ports:
      - "3100:3100"
    volumes:
      - ./services/logs-and-metric/config/loki/loki.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - LOKI_RETENTION_PERIOD=720h
    networks:
      - guide-network
    deploy:
      resources:
        limits:
          memory: 1g
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: guide-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./services/logs-and-metric/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    environment:
      - PROMETHEUS_SCRAPE_INTERVAL=15s
      - PROMETHEUS_SCRAPE_TIMEOUT=10s
      - MONITORING_ENVIRONMENT=prod
    networks:
      - guide-network
    deploy:
      resources:
        limits:
          memory: 2g
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: guide-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin123}
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN:-mypns.com}
      - GF_SERVER_ROOT_URL=https://${GRAFANA_DOMAIN:-mypns.com}:3000
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./services/logs-and-metric/config/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./services/logs-and-metric/config/grafana/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./services/logs-and-metric/config/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    networks:
      - guide-network
    deploy:
      resources:
        limits:
          memory: 1g
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
  grafana_data:
    driver: local
  prometheus_data:
    driver: local
  loki_data:
    driver: local

networks:
  guide-network:
    driver: bridge

