global:
  scrape_interval: 5s  # Более частый сбор для dev
  evaluation_interval: 5s
  scrape_timeout: 5s

# Правила для алертов (опционально)
rule_files:
  # - "alert_rules.yml"

scrape_configs:
  # Мониторинг самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Мониторинг Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: '/metrics'

  # Мониторинг Promtail
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
    metrics_path: '/metrics'

  # Мониторинг Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'

  # Автоматическое обнаружение Docker контейнеров с метриками (dev режим)
  - job_name: 'docker-containers-dev'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s  # Более частые обновления для dev
        filters:
          # Собираем метрики от всех контейнеров в dev режиме
          - name: label
            values: ["monitoring=enabled", "monitoring=dev"]
    relabel_configs:
      # Извлекаем имя контейнера
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container_name'
        regex: '/(.*)'
        replacement: '${1}'
      
      # Извлекаем имя образа
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image_name'
      
      # Извлекаем дополнительные labels
      - source_labels: ['__meta_docker_container_label_monitoring_service']
        target_label: 'service'
      
      - source_labels: ['__meta_docker_container_label_monitoring_environment']
        target_label: 'environment'
        replacement: 'dev'
      
      # Устанавливаем адрес для сбора метрик
      - source_labels: ['__meta_docker_container_label_monitoring_port']
        target_label: '__address__'
        regex: '(.+)'
        replacement: '${1}:${2}'
      
      # Если порт не указан, используем стандартный
      - source_labels: ['__meta_docker_container_ip', '__meta_docker_container_label_monitoring_port']
        target_label: '__address__'
        regex: '(.+);'
        replacement: '${1}:8080'
      
      # Устанавливаем путь к метрикам
      - source_labels: ['__meta_docker_container_label_monitoring_path']
        target_label: '__metrics_path__'
        replacement: '${1}'
      
      # Если путь не указан, используем стандартный
      - target_label: '__metrics_path__'
        replacement: '/metrics'
